version: '3'

services:
  app:
    image: ghcr.io/aurora-develop/aurora
    container_name: aurora
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
